### ISSUE TITLE
Failed to destroy zpool in tests.py

### ISSUE THREAD

**Issue by EchterAgo** [openzfsonwindows/openzfs#298]
First time I've seen this:

```
2023-10-18 14:56:11,083 - tests.tests - INFO - Drive letters after tank19 pool create: {'Data': WindowsPath('D:/'), 'tank19': WindowsPath('E:/')}
zunmount(tank19,E:/) running
zunmount(tank19,E:/) returns 0
2023-10-18 14:56:16,313 - tests.tests - INFO - Drive letters after tank20 pool create: {'Data': WindowsPath('D:/')}
cannot destroy 'tank20': pool is busy
Traceback (most recent call last):
  File "Y:\openzfs\contrib\windows\tests\utils.py", line 357, in allocated_files
    yield [f[0] for f in files]
  File "Y:\openzfs\contrib\windows\tests\tests.py", line 157, in main
    with zpool_create(ctx, f"tank{i}", paths_to_unc(bf[:1])) as pool:
  File "C:\Users\WDKRemoteUser\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 144, in __exit__
    next(self.gen)
  File "Y:\openzfs\contrib\windows\tests\utils.py", line 448, in zpool_create
    raise RuntimeError("Failed to destroy zpool")
RuntimeError: Failed to destroy zpool

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Y:\openzfs\contrib\windows\tests\tests.py", line 164, in <module>
    main()
  File "Y:\openzfs\contrib\windows\tests\tests.py", line 57, in main
    with allocated_files(
  File "C:\Users\WDKRemoteUser\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "Y:\openzfs\contrib\windows\tests\utils.py", line 360, in allocated_files
    os.remove(f[0])
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\testfolder\\test01.dat'
```

**Comment by EchterAgo** [comment]
Interesting that the pool has no drive letter after create: `Drive letters after tank20 pool create: {'Data': WindowsPath('D:/')}`

**Comment by EchterAgo** [comment]
The machine is for some reason running very slowly right now, it takes a few seconds to actually draw a newly opened explorer window for example. I think it is likely that this caused the test to fail. But I thought we test that the pool is actually created. Hmm.

**Comment by EchterAgo** [comment]
Explorer has an open handle to the pool and doesn't want to close it, that is why it isn't unmounted. At the time the destroy failed no explorer windows other than the taskbar/desktop were open. The handle was opened by the root `explorer.exe` process, not by  a subprocess.

**Comment by EchterAgo** [comment]
![image](https://github.com/openzfsonwindows/openzfs/assets/922233/ce76e924-a2ed-495a-8d12-c3bc64d9682b)

**Comment by EchterAgo** [comment]
The pool is not being actively written to anymore but I still see these in cbuf:

```
FFFFB10207562040: dprintf: zfs_vnops_windows.c:133:zfs_AcquireForLazyWrite(): zfs_AcquireForLazyWrite:fo FFFFBBB521C88730
FFFFB101956DB040: dprintf: zfs_vnops_windows.c:133:zfs_AcquireForLazyWrite(): zfs_AcquireForLazyWrite:fo FFFFB655C33293C0
FFFFB10207562040: dprintf: zfs_vnops_windows.c:136:zfs_AcquireForLazyWrite(): zfs_AcquireForLazyWrite: fo FFFFBBB521C88730 already freed zfsvfs
FFFFB101956DB040: dprintf: zfs_vnops_windows.c:136:zfs_AcquireForLazyWrite(): zfs_AcquireForLazyWrite: fo FFFFB655C33293C0 already freed zfsvfs
FFFFB10207562040: dprintf: zfs_vnops_windows.c:133:zfs_AcquireForLazyWrite(): zfs_AcquireForLazyWrite:fo FFFFB655C3327DE0
FFFFB101956DB040: dprintf: zfs_vnops_windows.c:133:zfs_AcquireForLazyWrite(): zfs_AcquireForLazyWrite:fo FFFFB101D805E1C0
FFFFB10207562040: dprintf: zfs_vnops_windows.c:136:zfs_AcquireForLazyWrite(): zfs_AcquireForLazyWrite: fo FFFFB655C3327DE0 already freed zfsvfs
FFFFB101956DB040: dprintf: zfs_vnops_windows.c:136:zfs_AcquireForLazyWrite(): zfs_AcquireForLazyWrite: fo FFFFB101D805E1C0 already freed zfsvfs
FFFFB10207562040: dprintf: zfs_vnops_windows.c:133:zfs_AcquireForLazyWrite(): zfs_AcquireForLazyWrite:fo FFFFB101D805FC50
FFFFB101956DB040: dprintf: zfs_vnops_windows.c:133:zfs_AcquireForLazyWrite(): zfs_AcquireForLazyWrite:fo FFFFB101D805B600
FFFFB10207562040: dprintf: zfs_vnops_windows.c:136:zfs_AcquireForLazyWrite(): zfs_AcquireForLazyWrite: fo FFFFB101D805FC50 already freed zfsvfs
FFFFB101956DB040: dprintf: zfs_vnops_windows.c:136:zfs_AcquireForLazyWrite(): zfs_AcquireForLazyWrite: fo FFFFB101D805B600 already freed zfsvfs
FFFFB10207562040: dprintf: zfs_vnops_windows.c:133:zfs_AcquireForLazyWrite(): zfs_AcquireForLazyWrite:fo FFFFB101D8060BF0
FFFFB101956DB040: dprintf: zfs_vnops_windows.c:133:zfs_AcquireForLazyWrite(): zfs_AcquireForLazyWrite:fo FFFFBBB52182EA10
FFFFB10207562040: dprintf: zfs_vnops_windows.c:136:zfs_AcquireForLazyWrite(): zfs_AcquireForLazyWrite: fo FFFFB101D8060BF0 already freed zfsvfs
FFFFB101956DB040: dprintf: zfs_vnops_windows.c:136:zfs_AcquireForLazyWrite(): zfs_AcquireForLazyWrite: fo FFFFBBB52182EA10 already freed zfsvfs
FFFFB10207562040: dprintf: zfs_vnops_windows.c:133:zfs_AcquireForLazyWrite(): zfs_AcquireForLazyWrite:fo FFFFB101D796CB10
FFFFB101D7CF5040: dprintf: zfs_vnops_windows.c:133:zfs_AcquireForLazyWrite(): zfs_AcquireForLazyWrite:fo FFFFB101D805FAC0
FFFFB101956DB040: dprintf: zfs_vnops_windows.c:133:zfs_AcquireForLazyWrite(): zfs_AcquireForLazyWrite:fo FFFFBBB521C89D10
FFFFB10207562040: dprintf: zfs_vnops_windows.c:136:zfs_AcquireForLazyWrite(): zfs_AcquireForLazyWrite: fo FFFFB101D796CB10 already freed zfsvfs
FFFFB101D7CF5040: dprintf: zfs_vnops_windows.c:136:zfs_AcquireForLazyWrite(): zfs_AcquireForLazyWrite: fo FFFFB101D805FAC0 already freed zfsvfs
FFFFB101956DB040: dprintf: zfs_vnops_windows.c:136:zfs_AcquireForLazyWrite(): zfs_AcquireForLazyWrite: fo FFFFBBB521C89D10 already freed zfsvfs
FFFFB10207562040: dprintf: zfs_vnops_windows.c:133:zfs_AcquireForLazyWrite(): zfs_AcquireForLazyWrite:fo FFFFB101D805C8C0
FFFFB1019560E240: dprintf: zfs_vnops_windows.c:133:zfs_AcquireForLazyWrite(): zfs_AcquireForLazyWrite:fo FFFFB101D8060D80
FFFFB10207562040: dprintf: zfs_vnops_windows.c:136:zfs_AcquireForLazyWrite(): zfs_AcquireForLazyWrite: fo FFFFB101D805C8C0 already freed zfsvfs
FFFFB101956DB040: dprintf: zfs_vnops_windows.c:133:zfs_AcquireForLazyWrite(): zfs_AcquireForLazyWrite:fo FFFFB101D7E7BBF0
FFFFB101956DB040: dprintf: zfs_vnops_windows.c:136:zfs_AcquireForLazyWrite(): zfs_AcquireForLazyWrite: fo FFFFB101D7E7BBF0 already freed zfsvfs
FFFFB1019560E240: dprintf: zfs_vnops_windows.c:136:zfs_AcquireForLazyWrite(): zfs_AcquireForLazyWrite: fo FFFFB101D8060D80 already freed zfsvfs
FFFFB101956DB040: dprintf: zfs_vnops_windows.c:133:zfs_AcquireForLazyWrite(): zfs_AcquireForLazyWrite:fo FFFFB101D7FB2A60
FFFFB101956DB040: dprintf: zfs_vnops_windows.c:136:zfs_AcquireForLazyWrite(): zfs_AcquireForLazyWrite: fo FFFFB101D7FB2A60 already freed zfsvfs
```

**Comment by EchterAgo** [comment]
`spa_refcount` is 12 and `spa_minref` is 11. Is there a way to find what is referencing it?

**Comment by lundman** [comment]
Hmm that is peculiar - wonder if its a new change or some rare thing

**Comment by EchterAgo** [comment]
It seems to be rare, the `tests.py` script looped quite some time before it was done and I've also seen this before I think, just didn't investigate it.

**Comment by EchterAgo** [comment]
So the threads that still call into `zfs_AcquireForLazyWrite` do so for a `WPSettings.dat` and for a `test01.file` which is created by the tests, but not the test where it hung. Interestingly the `vnode` always has `v_iocount==v_usecount==0`. What is also very curious is that `zmo!=vp->v_mount` and that both `zmo` and `vp->v_mount` are not named like a pool the `test01.file` could have been created in:

![image](https://github.com/openzfsonwindows/openzfs/assets/922233/eb65be01-aa24-4c4b-8044-bb0af0ac7477)

`Data` is my own pool to which I was copying data, I don't see why `test01.file` with exactly 1KiB size would be written there, same for `tank16` which is from the drive letter test in `tests.py`, no file should have been created on this pool.

**Comment by EchterAgo** [comment]
I wonder if this is something that only occurs when you have multiple pools? I'm testing with #297 so I can run a copy to my big pool and `tests.py` in a loop with backing files.

**Comment by EchterAgo** [comment]
So far this hasn't occurred again :\ Running the test for 3 hours now.

**Comment by lundman** [comment]
Side note, the cacheinit stuff was "desperation" code before we re-wrote the read/write/cleanup etc. It should now be retired
